CREATE TABLE IF NOT EXISTS pdf_downloads (
  id SERIAL PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  loan_amount VARCHAR(50) NOT NULL,
  download_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
